name: Run Lighthouse

on:
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          sudo apt-get install -y libnss3 libatk1.0-0 libx11-xcb1 libxcomposite1 libxrandr2 libxss1 libasound2 libpangocairo-1.0-0 libgtk-3-0

      - name: Check Chromium Version
        run: chromium-browser --version

      - name: Test URL Access
        run: curl -I https://www.yahoo.co.jp/

      - name: Install Lighthouse
        run: npm install -g lighthouse

      - name: Run Lighthouse
        run: lighthouse https://www.yahoo.co.jp/ --output=json --output-path=./lighthouse-report.json --quiet --chrome-flags="--headless"

      - name: Upload Lighthouse Report
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-report
          path: ./lighthouse-report.json
