name: Run Lighthouse

on:
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser libatk1.0-0 libx11-xcb1 libxcomposite1 libxrandr2 libxss1 libpangocairo-1.0-0 libgtk-3-0 --fix-missing

      - name: Test URL Access
        run: curl -I https://www.yahoo.co.jp/

      - name: Install Lighthouse
        run: npm install -g lighthouse

      - name: Run Lighthouse
        run: lighthouse https://www.yahoo.co.jp/ --output=json --output-path=./lighthouse-report.json --quiet --chrome-flags="--headless --disable-gpu --no-sandbox --disable-dev-shm-usage" --max-wait-for-load=60000

      - name: Upload Lighthouse Report
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-report
          path: ./lighthouse-report.json
